use_frameworks!

target 'NSStructMapper_Example' do
  pod 'NSStructMapper', :path => '../'
  pod 'Runtime', '~> 2.1.1'
  
  target 'NSStructMapper_Tests' do
    inherit! :search_paths

    
  end
end
